# Xyne Automation Framework Configuration
# Environment: local

# Application URLs
baseUrl: "https://xyne.juspay.net"
apiBaseUrl: "https://xyne.juspay.net/api"

# Browser settings
browser: "chromium"
headless: false

# Viewport settings
viewport:
  width: 1920
  height: 1080

# Timeout settings (in milliseconds)
timeout:
  action: 30000
  navigation: 30000
  test: 60000

# LLM Evaluation settings
llm:
  openaiApiKey: "${OPENAI_API_KEY}"
  model: "gpt-4"
  similarityThreshold: 0.7

# Performance thresholds
performance:
  maxResponseTime: 10
  maxErrorRate: 5

# Reporting settings
reporting:
  screenshotOnFailure: true
  videoRecording: false
  harRecording: false
