# Xyne Automation Framework Configuration
# Environment: local


# Browser settings
browser:
  type: "chromium"
  sharedMode: true
  sharedScope: "file"
  autoSequential: true
headless: false



# Timeout settings (in milliseconds)
timeout:
  action: 30000
  navigation: 30000
  test: 60000

# LLM Evaluation settings
llm:
  openaiApiKey: "${OPENAI_API_KEY}"
  model: "gpt-4"
  similarityThreshold: 0.7

# Performance thresholds
performance:
  maxResponseTime: 10
  maxErrorRate: 5

# Reporting settings
reporting:
  screenshotOnFailure: true
  videoRecording: false
  harRecording: false
